// quizQuestions.js

export const difficultyLevels = [
  "veryEasy",
  "easy",
  "medium",
  "hard",
  "veryHard",
];

export const quizQuestions = [
  {
    id: 1,
    image: "https://i.postimg.cc/CLbbq1nV/Ball-image.jpg",
    isAI: false,
    difficulty: "veryEasy",
  },
  {
    id: 2,
    image: "https://i.postimg.cc/K8FBr2tz/Chair-image.jpg",
    isAI: false,
    difficulty: "veryEasy",
  },
  {
    id: 3,
    image: "https://i.postimg.cc/0yxDdsD4/Pencil-image.jpg",
    isAI: false,
    difficulty: "veryEasy",
  },
  {
    id: 4,
    image: "https://i.postimg.cc/YCkYfHYV/Rock-image.jpg",
    isAI: false,
    difficulty: "veryEasy",
  },
  {
    id: 5,
    image: "https://i.postimg.cc/GmrGJCGV/Tree-image.jpg",
    isAI: false,
    difficulty: "veryEasy",
  },
  {
    id: 6,
    image: "https://i.postimg.cc/FHm3g40Y/Water-Bottle-Image.jpg",
    isAI: false,
    difficulty: "veryEasy",
  },
  {
    id: 7,
    image: "https://i.postimg.cc/j51BDg0r/ceiling-fans.jpg",
    isAI: false,
    difficulty: "easy",
  },
  {
    id: 8,
    image: "https://i.postimg.cc/3NYYfn1d/Facial-Recognisition-Img.jpg",
    isAI: true,
    aiType: "Think",
    difficulty: "easy",
  },
  {
    id: 9,
    image: "https://i.postimg.cc/wTx9h43Z/Gas-Stove-Img.jpg",
    isAI: false,
    difficulty: "easy",
  },
  {
    id: 10,
    image: "https://i.postimg.cc/bwW8fzgW/Map-Img.jpg",
    isAI: true,
    aiType: ["Decide","Recognize"],
    difficulty: "easy",
  },
  {
    id: 11,
    image: "https://i.postimg.cc/0QdqS7sF/Microwave-Img.jpg",
    isAI: false,
    difficulty: "easy",
  },
  {
    id: 12,
    image: "https://i.postimg.cc/HWzgs03q/Watch-Img.jpg",
    isAI: false,
    difficulty: "easy",
  },
  
  {
    id: 13,
    image: "https://i.postimg.cc/Xq7tyhxk/cctv-image.jpg",
    isAI: true,
    aiType: "Recognize",
    difficulty: "medium",
  },
  {
    id: 14,
    image: "https://i.postimg.cc/dtfgL5CN/fingerprint-scanner-img.jpg",
    isAI: true,
    aiType: "Recognize",
    difficulty: "medium",  
  },
  {
    id: 15,
    image: "https://i.postimg.cc/KzQHFfFf/netflix-recommendation-img.jpg",
    isAI: true,
    aiType: "Think",
    difficulty: "medium",  
  },
  {
    id: 16,
    image: "https://i.postimg.cc/nzwG0Pp3/self-checkout-machine-img.jpg",
    isAI: true,
    aiType:["Learn","Decide"],
    difficulty: "medium",  
  },
  {
    id: 17,
    image: "https://i.postimg.cc/WpCQ49gF/siri-image.jpg",
    isAI: true,
    aiType:["Recognize","Decide"],
    difficulty: "medium",  
  },
  {
    id: 18,
    image: "https://i.postimg.cc/KYGWWCSJ/youtube-recommendation-img.png",
    isAI: true,
    aiType:["Learn","Decide"],
    difficulty: "medium",  
  },
  {
    id: 19,
    image: "https://i.postimg.cc/MK1rpzWk/autonomus-car-img.jpg",
    isAi: true,
    aiType:["Recognize","Decide","Think",],
    difficulty: "hard",
  },
  {
    id: 20,
    image: "https://i.postimg.cc/4dKWkgLR/color-sorting-arm.jpg",
    isAi: true,
    aiType:["Recognize","Decide",],
    difficulty: "hard",
  },
  {
    id: 21,
    image: "https://i.postimg.cc/MHVtHYJg/doctor-using-holographic-technology-examine-heart.jpg",
    isAi: true,
    aiType:["Recognize","Decide",],
    difficulty: "hard",
  },
  {
    id: 22,
    image: "https://i.postimg.cc/dtR4KnBP/email-spam-filter-img.jpg",
    isAi: true,
    aiType:["Learn","Decide",],
    difficulty: "hard",
  },
  {
    id: 23,
    image: "https://i.postimg.cc/3NYYfn1d/Facial-Recognisition-Img.jpg",
    isAi: true,
    aiType:["Recognize",],
    difficulty: "hard",
  },
  {
    id: 24,
    image: "hhttps://i.postimg.cc/NjzThrW2/opened-ai-chat-laptop.jpg",
    isAi: true,
    aiType:["Learn","Think"],
    difficulty: "hard",
  },
  {
    id: 25,
    image: "https://i.postimg.cc/ZKD00zVt/AI-Analyzing-climate-img.jpg",
    isAi: true,
    aiType:["Learn","Think"],
    difficulty: "veryHard",
  },
  {
    id: 26,
    image: "https://i.postimg.cc/MK1rpzWk/autonomus-car-img.jpg",
    isAi: true,
    aiType:["Recognize","Decide","Think"],
    difficulty: "veryHard",
  },
  {
    id: 27,
    image: "https://i.postimg.cc/h42t3Rk3/convesational-robot-img.jpg",
    isAi: true,
    aiType:["Recognize","Learn","Think"],
    difficulty: "veryHard",
  },
  {
    id: 28,
    image: "https://i.postimg.cc/rp2VtV4d/Fraud-detection-banking-img.jpg",
    isAi: true,
    aiType:["Learn","Decide",],
    difficulty: "veryHard",
  },
  {
    id: 29,
    image: "https://i.postimg.cc/SsDk5cPF/stock-market-graph-img.jpg",
    isAi: true,
    aiType:["Learn","Think"],
    difficulty: "veryHard",
  },
  {
    id: 30,
    image: "https://i.postimg.cc/DwLFh9Ny/text-to-image-ai-img.jpg",
    isAi: true,
    aiType:["Learn","Think"],
    difficulty: "veryHard",
  },

];

